spring.datasource.url=jdbc:postgresql://dpg-d6rt0c75gffc7388hkt0-a.oregon-postgres.render.com/studygroup_db_evfz
spring.datasource.username=studygroup_db_evfz_user
spring.datasource.password=vSSyAGR2oHs1lS1Sl2RYa7kSq6GwrpdG

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080